### PR TITLE
provide strsep for parse_kwargs

### PR DESCRIPTION
**Pull request by guruofquality**
I didnt have strsep() on MSVC. Found an implementation here: http://unixpapa.com/incnote/string.html

### CODE REVIEW

**Comment by rxseger** [comment]
Thanks! Didn't realize strsep wasn't portable but I see https://www.gnu.org/software/gnulib/manual/html_node/strsep.html has the cautionary note "This function is missing on some platforms: AIX 4.3.2, HP-UX 11, IRIX 6.5, OSF/1 5.1, Solaris 10, mingw, MSVC 9, BeOS"

**Comment by guruofquality** [comment]
FYI - https://github.com/pothosware/SoapySDR/issues/87

**Comment by rxseger** [comment]
@guruofquality Commented there. Thanks again for these Windows support fixes, I really ought to get a Windows VM or CI system setup to catch these incompatibilities sometime.

Hey do you have any insight into this problem: https://www.reddit.com/r/RTLSDR/comments/4tpxv7/rx_tools_commandline_sdr_tools_for_rtlsdr_bladerf/d5lwd2j - if you can help @KalenXI he says: "I've been trying with cmake and Visual Studio for the past few hours without any success. The problem seems to be that PothosSDR only provides 64-bit versions of SoapySDR and pthreads. But rx_tools won't compile if I set the architecture to 64-bit. I was able to recompile SoapySDR for 32-bit and point the cmake file to that instead but it's still pulling pthreads from PothosSDR's 64-bit version."

**Comment by guruofquality** [comment]
> Commented there. Thanks again for these Windows support fixes, I really ought to get a Windows VM or CI system setup to catch these incompatibilities sometime.

I'm using a free service [appveyor for SoapySDR](https://github.com/pothosware/SoapySDR/blob/master/appveyor.yml), just like travis for for windows. And here is an example, though now commented out, of pothos [compiling SoapySDR as a dependency](https://github.com/pothosware/pothos/blob/master/appveyor.yml#L38) -- so you might be able to copy these and come up with a working appveyor config for rx tools.

> But rx_tools won't compile if I set the architecture to 64-bit. I was able to recompile SoapySDR for 32-bit and point the cmake file to that instead but it's still pulling pthreads from PothosSDR's 64-bit version." 

No idea, I would have to see the error.  But I'm building rx_tools just fine [in PothosSDR](https://github.com/pothosware/PothosSDR/blob/master/BuildSoapySDR.cmake#L283) and the latest installer now has rx-tools (before the kwargs parser addition with the unknown string function).

**Comment by KalenXI** [comment]
Didn't realize rx_tools was already in PothosSDR. That's much easier :smiley: 

Anyway, here's what I'm getting trying to compile it.

First I run cmake -G "Visual Studio 14 2015 Win64" .
```
C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master>cmake -G "Visual Studio 14 2015 Win64" .
-- The C compiler identification is MSVC 19.0.23918.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Build type not specified: defaulting to release.
-- Found Threads: C:/Program Files/PothosSDR/lib/pthreadVC2.lib
-- THREADS_PTHREADS_INCLUDE_DIR: C:/Program Files/PothosSDR/include
-- CMAKE_THREAD_LIBS_INIT: C:/Program Files/PothosSDR/lib/pthreadVC2.lib
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/KalenXI/Downloads/rx_tools-master/rx_tools-master
```

And this is the output I get when attempting to build in VS

```
1>------ Build started: Project: ZERO_CHECK, Configuration: Debug x64 ------
1>  Checking Build System
1>  CMake does not need to re-run because C:/Users/KalenXI/Downloads/rx_tools-master/rx_tools-master/CMakeFiles/generate.stamp is up-to-date.
2>------ Build started: Project: common, Configuration: Debug x64 ------
2>  Building Custom Rule C:/Users/KalenXI/Downloads/rx_tools-master/rx_tools-master/CMakeLists.txt
2>  CMake does not need to re-run because C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\CMakeFiles\generate.stamp is up-to-date.
2>  getopt.c
2>  convenience.c
2>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\getopt\getopt.c(401): warning C4996: 'getenv': This function or variable may be unsafe. Consider using _dupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
2>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdlib.h(1183): note: see declaration of 'getenv'
2>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\convenience\convenience.c(45): warning C4996: 'localtime': This function or variable may be unsafe. Consider using localtime_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
2>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\time.h(505): note: see declaration of 'localtime'
2>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\convenience\convenience.c(58): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
2>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\convenience\convenience.c(85): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
2>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\convenience\convenience.c(111): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
2>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\convenience\convenience.c(404): warning C4996: 'dup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _dup. See online help for details.
2>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\corecrt_io.h(468): note: see declaration of 'dup'
2>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\convenience\convenience.c(405): warning C4996: 'dup2': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _dup2. See online help for details.
2>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\corecrt_io.h(473): note: see declaration of 'dup2'
2>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\convenience\convenience.c(415): warning C4996: 'dup2': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _dup2. See online help for details.
2>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\corecrt_io.h(473): note: see declaration of 'dup2'
2>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\convenience\convenience.c(426): warning C4101: 's2': unreferenced local variable
2>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\convenience\convenience.c(425): warning C4101: 'offset': unreferenced local variable
2>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\convenience\convenience.c(427): warning C4101: 'serial': unreferenced local variable
2>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\convenience\convenience.c(427): warning C4101: 'vendor': unreferenced local variable
2>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\convenience\convenience.c(425): warning C4101: 'device': unreferenced local variable
2>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\convenience\convenience.c(427): warning C4101: 'product': unreferenced local variable
2>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\convenience\convenience.c(542): warning C4013: 'strsep' undefined; assuming extern returning int
2>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\convenience\convenience.c(542): warning C4047: '=': 'char *' differs in levels of indirection from 'int'
2>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\convenience\convenience.c(540): warning C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details.
2>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\string.h(552): note: see declaration of 'strdup'
2>c:\users\KalenXI\downloads\rx_tools-master\rx_tools-master\src\convenience\convenience.c(187): warning C4700: uninitialized local variable 'r' used
2>  common.vcxproj -> C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\Debug\common.lib
3>------ Build started: Project: rx_fm, Configuration: Debug x64 ------
4>------ Build started: Project: rx_power, Configuration: Debug x64 ------
5>------ Build started: Project: rx_sdr, Configuration: Debug x64 ------
3>  Building Custom Rule C:/Users/KalenXI/Downloads/rx_tools-master/rx_tools-master/CMakeLists.txt
3>  CMake does not need to re-run because C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\CMakeFiles\generate.stamp is up-to-date.
3>  rtl_fm.c
4>  Building Custom Rule C:/Users/KalenXI/Downloads/rx_tools-master/rx_tools-master/CMakeLists.txt
4>  CMake does not need to re-run because C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\CMakeFiles\generate.stamp is up-to-date.
5>  Building Custom Rule C:/Users/KalenXI/Downloads/rx_tools-master/rx_tools-master/CMakeLists.txt
5>  CMake does not need to re-run because C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\CMakeFiles\generate.stamp is up-to-date.
4>  rtl_power.c
3>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\rtl_fm.c(690): warning C4244: '=': conversion from 'int64_t' to 'int', possible loss of data
3>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\rtl_fm.c(710): warning C4244: '=': conversion from 'int64_t' to 'int', possible loss of data
3>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\rtl_fm.c(711): warning C4244: '=': conversion from 'int64_t' to 'int', possible loss of data
3>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\rtl_fm.c(845): warning C4244: '=': conversion from 'double' to 'int16_t', possible loss of data
3>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\rtl_fm.c(1431): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
5>  rtl_sdr.c
3>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(205): note: see declaration of 'fopen'
3>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\rtl_fm.c(1414): warning C4101: 'r': unreferenced local variable
3>c:\users\KalenXI\downloads\rx_tools-master\rx_tools-master\src\rtl_fm.c(1456): warning C4700: uninitialized local variable 'r' used
3>common.lib(convenience.obj) : error LNK2019: unresolved external symbol strsep referenced in function parse_kwargs
3>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\Debug\rx_fm.exe : fatal error LNK1120: 1 unresolved externals
4>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\rtl_power.c(444): warning C4244: '=': conversion from 'double' to 'int64_t', possible loss of data
4>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\rtl_power.c(445): warning C4244: '=': conversion from 'double' to 'int64_t', possible loss of data
4>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\rtl_power.c(446): warning C4244: '=': conversion from 'double' to 'int64_t', possible loss of data
4>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\rtl_power.c(472): warning C4244: 'function': conversion from 'int64_t' to 'double', possible loss of data
4>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\rtl_power.c(473): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
4>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\rtl_power.c(484): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
4>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\rtl_power.c(493): warning C4244: '=': conversion from 'int64_t' to 'int', possible loss of data
4>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\rtl_power.c(501): warning C4244: '=': conversion from 'int64_t' to 'int', possible loss of data
4>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\rtl_power.c(509): warning C4244: '=': conversion from 'int64_t' to 'int', possible loss of data
4>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\rtl_power.c(513): warning C4244: '=': conversion from 'int64_t' to 'int', possible loss of data
4>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\rtl_power.c(514): warning C4244: '=': conversion from 'int64_t' to 'int', possible loss of data
4>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\rtl_power.c(515): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
4>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\rtl_power.c(546): warning C4101: 'n_read': unreferenced local variable
4>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\rtl_power.c(833): warning C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details.
4>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\string.h(552): note: see declaration of 'strdup'
4>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\rtl_power.c(979): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
4>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(205): note: see declaration of 'fopen'
4>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\rtl_power.c(1001): warning C4996: 'tzset': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _tzset. See online help for details.
4>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\time.h(593): note: see declaration of 'tzset'
5>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\rtl_sdr.c(285): warning C4244: '=': conversion from 'double' to 'uint8_t', possible loss of data
5>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\rtl_sdr.c(293): warning C4244: '=': conversion from 'double' to 'uint8_t', possible loss of data
5>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\rtl_sdr.c(230): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
5>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(205): note: see declaration of 'fopen'
5>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\src\rtl_sdr.c(94): warning C4101: 'n_read': unreferenced local variable
4>common.lib(convenience.obj) : error LNK2019: unresolved external symbol strsep referenced in function parse_kwargs
4>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\Debug\rx_power.exe : fatal error LNK1120: 1 unresolved externals
5>common.lib(convenience.obj) : error LNK2019: unresolved external symbol strsep referenced in function parse_kwargs
5>C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\Debug\rx_sdr.exe : fatal error LNK1120: 1 unresolved externals
6>------ Build started: Project: ALL_BUILD, Configuration: Debug x64 ------
6>  Building Custom Rule C:/Users/KalenXI/Downloads/rx_tools-master/rx_tools-master/CMakeLists.txt
6>  CMake does not need to re-run because C:\Users\KalenXI\Downloads\rx_tools-master\rx_tools-master\CMakeFiles\generate.stamp is up-to-date.
7>------ Skipped Build: Project: INSTALL, Configuration: Debug x64 ------
7>Project not selected to build for this solution configuration 
========== Build: 3 succeeded, 3 failed, 0 up-to-date, 1 skipped ==========
```

The specific error is: error LNK2019: unresolved external symbol strsep referenced in function parse_kwargs

**Comment by KalenXI** [comment]
Actually reading back through this pull it looks like this is actually the error it is supposed to fix. I just happened to download the source a few hours before it was merged. I'll try it again with this commit

**Comment by guruofquality** [comment]
> The specific error is: error LNK2019: unresolved external symbol strsep referenced in function parse_kwargs

Yup, this should be fixed now in this exact pull request

Also, big warning here. The PothosSDR libs are all build with Release or RelWithDebInfo build mode. You will need to to do the same for rx-tools or things will segfault because of ABI mismatch

**Pull request merged**
